version: "3.5"
services:
  geth:
    build:
      context: geth
      args:
        UPSTREAM_VERSION: v1.13.6
    volumes:
      - "data:/data"
    ports:
      - "31403:31403/tcp"
      - "31403:31403/udp"
    restart: unless-stopped
    environment:
      - GETH_HTTP=true
      - GETH_HTTP_ADDR=0.0.0.0
      - GETH_HTTP_CORSDOMAIN=*
      - GETH_HTTP_VHOSTS=*
      - "GETH_HTTP_API=eth,engine,net,web3,txpool"
      - GETH_SYNCMODE=snap
      - GETH_WS=true
      - GETH_WS_ADDR=0.0.0.0
      - GETH_PORT=31403
      - GETH_METRICS=true
      - GETH_METRICS_ADDR=0.0.0.0
      - GETH_STATE_SCHEME=path
      - EXTRA_FLAGS
    image: "geth.holesky-geth.dnp.dappnode.eth:0.1.0"
volumes:
  data: {}
